# Kafka Event Schemas for Event-Driven Architecture
# Feature: 002-event-driven
# Version: 1.0

openapi: 3.1.0
info:
  title: Task Management Event Schemas
  version: 1.0.0
  description: |
    Kafka event schemas for event-driven task management system.
    All events are published to Redpanda Cloud Kafka topics as JSON.

components:
  schemas:
    # Base Event Schema
    BaseEvent:
      type: object
      required:
        - event_id
        - event_type
        - timestamp
        - user_id
        - schema_version
      properties:
        event_id:
          type: string
          format: uuid
          description: Unique event identifier (UUID v4)
          example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
        event_type:
          type: string
          description: Event type identifier
          enum:
            - task.created
            - task.completed
            - task.updated
            - task.deleted
            - reminder.sent
        timestamp:
          type: string
          format: date-time
          description: Event creation timestamp (UTC)
          example: "2025-01-15T10:30:00Z"
        user_id:
          type: integer
          description: User ID who triggered the event
          minimum: 1
          example: 42
        schema_version:
          type: string
          description: Event schema version for future evolution
          default: "1.0"
          example: "1.0"

    # TaskCreatedEvent
    TaskCreatedEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          required:
            - task_id
            - title
          properties:
            event_type:
              type: string
              const: "task.created"
            task_id:
              type: integer
              description: ID of the created task
              minimum: 1
              example: 101
            title:
              type: string
              description: Task title
              maxLength: 255
              example: "Weekly team meeting"
            description:
              type: string
              nullable: true
              description: Task description
              example: "Discuss project progress and blockers"
            priority:
              type: string
              nullable: true
              enum: [low, medium, high, null]
              description: Task priority level
              example: "high"
            due_date:
              type: string
              format: date-time
              nullable: true
              description: Task due date (UTC)
              example: "2025-01-20T14:00:00Z"
            recurrence_rule:
              type: string
              nullable: true
              description: iCalendar RRULE format for recurring tasks
              example: "FREQ=WEEKLY;BYDAY=MO"
            category_id:
              type: integer
              nullable: true
              description: Category ID
              minimum: 1
              example: 5
            tag_ids:
              type: array
              items:
                type: integer
                minimum: 1
              description: List of tag IDs
              default: []
              example: [1, 3]
      x-kafka-topic: task-events
      x-partition-key: task_id

    # TaskCompletedEvent
    TaskCompletedEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          required:
            - task_id
            - completed_at
          properties:
            event_type:
              type: string
              const: "task.completed"
            task_id:
              type: integer
              description: ID of the completed task
              minimum: 1
              example: 101
            recurrence_rule:
              type: string
              nullable: true
              description: Recurrence rule if task is recurring
              example: "FREQ=WEEKLY;BYDAY=MO"
            completed_at:
              type: string
              format: date-time
              description: Completion timestamp (UTC)
              example: "2025-01-15T16:45:00Z"
      x-kafka-topic: task-recurrence
      x-partition-key: task_id

    # TaskUpdatedEvent
    TaskUpdatedEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          required:
            - task_id
            - updated_fields
          properties:
            event_type:
              type: string
              const: "task.updated"
            task_id:
              type: integer
              description: ID of the updated task
              minimum: 1
              example: 101
            updated_fields:
              type: object
              description: Map of field names to new values
              additionalProperties: true
              example:
                due_date: "2025-01-22T14:00:00Z"
                priority: "medium"
      x-kafka-topic: task-events
      x-partition-key: task_id

    # TaskDeletedEvent
    TaskDeletedEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          required:
            - task_id
          properties:
            event_type:
              type: string
              const: "task.deleted"
            task_id:
              type: integer
              description: ID of the deleted task
              minimum: 1
              example: 101
      x-kafka-topic: task-events
      x-partition-key: task_id

    # ReminderSentEvent
    ReminderSentEvent:
      allOf:
        - $ref: '#/components/schemas/BaseEvent'
        - type: object
          required:
            - task_id
            - reminder_time
          properties:
            event_type:
              type: string
              const: "reminder.sent"
            task_id:
              type: integer
              description: ID of the task for which reminder was sent
              minimum: 1
              example: 101
            reminder_time:
              type: string
              format: date-time
              description: When the reminder was sent (UTC)
              example: "2025-01-20T13:00:00Z"
      x-kafka-topic: task-reminders
      x-partition-key: task_id

# Kafka Topic Configuration
x-kafka-topics:
  task-events:
    partitions: 3
    replication_factor: 1
    retention_ms: 604800000  # 7 days
    cleanup_policy: delete
    description: Task lifecycle events (create, update, delete)
    producers:
      - MCP Tools (add_task, update_task, delete_task)
    consumers:
      - Notification Service

  task-reminders:
    partitions: 1
    replication_factor: 1
    retention_ms: 86400000  # 1 day
    cleanup_policy: delete
    description: Reminder notifications (audit trail)
    producers:
      - Notification Service
    consumers:
      - (Future: Email/SMS notification service)

  task-recurrence:
    partitions: 1
    replication_factor: 1
    retention_ms: 604800000  # 7 days
    cleanup_policy: delete
    description: Recurring task regeneration events
    producers:
      - MCP Tools (complete_task)
    consumers:
      - Recurring Task Service

# Producer Configuration
x-kafka-producer-config:
  acks: 1  # At-least-once delivery
  enable_idempotence: true
  compression_type: gzip
  max_request_size: 1048576  # 1MB
  retries: 3
  retry_backoff_ms: 100

# Consumer Configuration
x-kafka-consumer-config:
  auto_offset_reset: earliest
  enable_auto_commit: false  # Manual commit after processing
  max_poll_records: 100
  session_timeout_ms: 30000
  heartbeat_interval_ms: 3000
