"""add_performance_indexes_for_task_filtering_and_sorting

Revision ID: 289315d71f63
Revises: 38ae4c3ca0ff
Create Date: 2025-12-13 10:18:48.000024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '289315d71f63'
down_revision = '38ae4c3ca0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all required changes are included in the initial migration
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all required changes are included in the initial migration
    pass
    # ### end Alembic commands ###
