"""Add reminder, web_vital, analytics_event, task_order, and user_subscription models

Revision ID: 38ae4c3ca0ff
Revises: 89c704a27f92
Create Date: 2025-12-13 07:52:53.511986

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38ae4c3ca0ff'
down_revision = '89c704a27f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all tables are included in the initial migration
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all tables are included in the initial migration
    pass
    # ### end Alembic commands ###
