"""Add recurring task support fields

Revision ID: 89c704a27f92
Revises: 4eaae8f8cbbc
Create Date: 2025-12-13 01:36:32.117288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89c704a27f92'
down_revision = '4eaae8f8cbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add recurring task support columns
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring_instance', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('occurrence_date', sa.DateTime(), nullable=True))

    # Set default value for existing rows
    op.execute('UPDATE tasks SET is_recurring_instance = false WHERE is_recurring_instance IS NULL')

    # Now make is_recurring_instance NOT NULL
    op.alter_column('tasks', 'is_recurring_instance', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_tasks_is_recurring_instance'), 'tasks', ['is_recurring_instance'], unique=False)
    op.create_index(op.f('ix_tasks_occurrence_date'), 'tasks', ['occurrence_date'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)

    # Create foreign key constraint
    op.create_foreign_key('fk_tasks_parent_task_id', 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint
    op.drop_constraint('fk_tasks_parent_task_id', 'tasks', type_='foreignkey')

    # Drop indexes
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_occurrence_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_recurring_instance'), table_name='tasks')

    # Drop columns
    op.drop_column('tasks', 'occurrence_date')
    op.drop_column('tasks', 'is_recurring_instance')
    op.drop_column('tasks', 'parent_task_id')
    # ### end Alembic commands ###
