"""Add recurring task support fields

Revision ID: 89c704a27f92
Revises: 4eaae8f8cbbc
Create Date: 2025-12-13 01:36:32.117288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89c704a27f92'
down_revision = '4eaae8f8cbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all recurring task fields are included in the initial migration
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all recurring task fields are included in the initial migration
    pass
    # ### end Alembic commands ###
