"""Description

Revision ID: b84ceae54ecb
Revises: 289315d71f63
Create Date: 2025-12-14 01:50:47.756262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b84ceae54ecb'
down_revision = '289315d71f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all required changes are included in the initial migration
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is now a no-op since all required changes are included in the initial migration
    pass
    # ### end Alembic commands ###
