"""Description

Revision ID: b84ceae54ecb
Revises: 289315d71f63
Create Date: 2025-12-14 01:50:47.756262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b84ceae54ecb'
down_revision = '289315d71f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('p256dh_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.add_column('user_subscriptions', sa.Column('auth_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.drop_column('user_subscriptions', 'subscription_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('subscription_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_subscriptions', 'auth_key')
    op.drop_column('user_subscriptions', 'p256dh_key')
    # ### end Alembic commands ###
