"""Initial migration with all tables

Revision ID: dfd778d535ec
Revises:
Create Date: 2025-12-13 00:11:33.463649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'dfd778d535ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Better Auth tables (user, account, session, verification) are NOT managed by this migration
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('categories', 'color',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=7),
               existing_nullable=True)
    op.alter_column('categories', 'user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('idx_categories_user_id'), table_name='categories')
    op.drop_constraint(op.f('uq_categories_user_name_type'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('tags', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('tags', 'user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.drop_index(op.f('idx_tags_user_id'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.drop_constraint(op.f('tags_user_id_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.drop_column('tags', 'created_at')
    op.drop_column('tags', 'updated_at')
    op.drop_index(op.f('idx_task_tag_link_tag'), table_name='task_tag_link')
    op.drop_index(op.f('idx_task_tag_link_task'), table_name='task_tag_link')
    op.drop_constraint(op.f('task_tag_link_task_id_fkey'), 'task_tag_link', type_='foreignkey')
    op.drop_constraint(op.f('task_tag_link_tag_id_fkey'), 'task_tag_link', type_='foreignkey')
    op.create_foreign_key(None, 'task_tag_link', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'task_tag_link', 'tags', ['tag_id'], ['id'])
    op.alter_column('tasks', 'user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('idx_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_title'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_completed'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_priority'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('idx_tasks_user_status'), 'tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_tasks_user_priority'), 'tasks', ['user_id', 'priority'], unique=False)
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_tasks_user_due_date'), 'tasks', ['user_id', 'due_date'], unique=False)
    op.create_index(op.f('idx_tasks_user_completed'), 'tasks', ['user_id', 'completed'], unique=False)
    op.create_index(op.f('idx_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('idx_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'task_tag_link', type_='foreignkey')
    op.drop_constraint(None, 'task_tag_link', type_='foreignkey')
    op.create_foreign_key(op.f('task_tag_link_tag_id_fkey'), 'task_tag_link', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('task_tag_link_task_id_fkey'), 'task_tag_link', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_task_tag_link_task'), 'task_tag_link', ['task_id'], unique=False)
    op.create_index(op.f('idx_task_tag_link_tag'), 'task_tag_link', ['tag_id'], unique=False)
    op.add_column('tags', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tags', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_user_id_fkey'), 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('idx_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.alter_column('tags', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tags', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tags', 'color')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_unique_constraint(op.f('uq_categories_user_name_type'), 'categories', ['user_id', 'name', 'type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.alter_column('categories', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'color',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=7),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # Note: Better Auth tables (user, account, session, verification) are NOT managed by this migration
    # ### end Alembic commands ###
