"""Add CASCADE DELETE to task_orders task_id foreign key

Revision ID: e9dd75f0acbf
Revises: b84ceae54ecb
Create Date: 2025-12-14 05:13:47.972079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9dd75f0acbf'
down_revision = 'b84ceae54ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add CASCADE DELETE to task_orders task_id foreign key
    op.drop_constraint(op.f('task_orders_task_id_fkey'), 'task_orders', type_='foreignkey')
    op.create_foreign_key(None, 'task_orders', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove CASCADE DELETE from task_orders task_id foreign key
    op.drop_constraint(None, 'task_orders', type_='foreignkey')
    op.create_foreign_key(op.f('task_orders_task_id_fkey'), 'task_orders', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
