"""add_missing_indexes_and_fix_constraints

Revision ID: 64209b51956d
Revises: 235c26e8b87a
Create Date: 2025-12-09 11:03:03.764342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64209b51956d'
down_revision = '235c26e8b87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create indexes if they don't exist (handle case where SQLModel already created them)
    conn = op.get_bind()

    # Check and create ix_tags_name
    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_tags_name'"))
    if not result.fetchone():
        op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)

    # Check and create unique constraint uq_tag_name_user
    result = conn.execute(sa.text("SELECT 1 FROM pg_constraint WHERE conname = 'uq_tag_name_user'"))
    if not result.fetchone():
        op.create_unique_constraint('uq_tag_name_user', 'tags', ['name', 'user_id'])

    # Check and create ix_tasks_title
    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_tasks_title'"))
    if not result.fetchone():
        op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)

    # Add performance indexes for filtering and sorting as per data-model.md
    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_tasks_user_completed'"))
    if not result.fetchone():
        op.create_index('idx_tasks_user_completed', 'tasks', ['user_id', 'completed'])

    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_tasks_user_priority'"))
    if not result.fetchone():
        op.create_index('idx_tasks_user_priority', 'tasks', ['user_id', 'priority'])

    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_tasks_user_due_date'"))
    if not result.fetchone():
        op.create_index('idx_tasks_user_due_date', 'tasks', ['user_id', 'due_date'])

    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_task_tag_link_task'"))
    if not result.fetchone():
        op.create_index('idx_task_tag_link_task', 'task_tag_link', ['task_id'])

    result = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_task_tag_link_tag'"))
    if not result.fetchone():
        op.create_index('idx_task_tag_link_tag', 'task_tag_link', ['tag_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop performance indexes
    op.drop_index('idx_task_tag_link_tag', table_name='task_tag_link')
    op.drop_index('idx_task_tag_link_task', table_name='task_tag_link')
    op.drop_index('idx_tasks_user_due_date', table_name='tasks')
    op.drop_index('idx_tasks_user_priority', table_name='tasks')
    op.drop_index('idx_tasks_user_completed', table_name='tasks')

    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_constraint('uq_tag_name_user', 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    # ### end Alembic commands ###
